version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Tallinn
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"
