import { Wrapping, type Wrapping as WrappingMode } from "../core/Constants.ts";
import { EventDispatcher } from "../core/EventDispatcher.ts";
import { Matrix3 } from "../math/Matrix3.ts";
import { Vector2 } from "../math/Vector2.ts";
import type { ImageDataLike, ImagePixelArray } from "../utils/ImageUtils.ts";
import {
  Source,
  type SourceImage,
  type SourceSerializationMeta,
} from "./Source.ts";

const MAX_SIZE = 128;
/** Number of CPU brightness variants generated by buildBrightnessLevels(). */
export const TEXTURE_BRIGHTNESS_LEVELS = 4;
const UV_MAPPING = 300;
const DEFAULT_NEAREST_FILTER = 1003;
const DEFAULT_RGBA_FORMAT = 1023;
const DEFAULT_UNSIGNED_BYTE_TYPE = 1009;
const DEFAULT_NO_COLOR_SPACE = "";
/** Default anisotropy value for CPU-sampled textures; always 1 on the nearest-neighbour path. */
export const DEFAULT_ANISOTROPY = 1;

/** Default image placeholder used when no source is supplied; always `undefined`. */
export const DEFAULT_IMAGE: undefined = undefined;

/** Default UV mapping mode for textures; matches the THREE.js UVMapping constant. */
export const DEFAULT_MAPPING = UV_MAPPING;

let textureId = 0;

/** Image or CPU pixel payload accepted by a texture. */
export type TextureImageSource = SourceImage;

/** Serializable texture parameters and source reference. */
export interface TextureJSON {
  /** Serialization metadata. */
  metadata: {
    /** Metadata version. */
    version: number;
    /** Serialized object kind. */
    type: string;
    /** Serialization generator label. */
    generator: string;
  };
  /** Stable texture identifier. */
  uuid: string;
  /** Display name. */
  name: string;
  /** Serialized source UUID. */
  image: string;
  /** Mapping mode. */
  mapping: number;
  /** UV channel. */
  channel: number;
  /** Repeat vector. */
  repeat: [number, number];
  /** Offset vector. */
  offset: [number, number];
  /** Rotation center. */
  center: [number, number];
  /** Rotation in radians. */
  rotation: number;
  /** Horizontal and vertical wrapping. */
  wrap: [number, number];
  /** Pixel format. */
  format: number;
  /** Optional internal pixel format. */
  internalFormat: string | undefined;
  /** Typed-array sample type recorded for serialization and validation. */
  type: number;
  /** Whether integer data is normalized. */
  normalized: boolean;
  /** Color space label. */
  colorSpace: string;
  /** Minification selector retained for nearest-neighbour compatibility. */
  minFilter: number;
  /** Magnification selector retained for nearest-neighbour compatibility. */
  magFilter: number;
  /** Anisotropy is fixed to one by the CPU sampler. */
  anisotropy: number;
  /** Vertical upload flip. */
  flipY: boolean;
  /** Alpha premultiplication request. */
  premultiplyAlpha: boolean;
  /** Pixel row unpack alignment. */
  unpackAlignment: number;
  /** Optional user metadata. */
  userData?: Record<string, unknown>;
}

/** Metadata container used to deduplicate serialized textures and images. */
export interface TextureSerializationMeta extends SourceSerializationMeta {
  /** Serialized textures keyed by UUID. */
  textures: Record<string, TextureJSON>;
}

/** A CPU-sampled texture with a hard 128x128 cache limit. */
export class Texture extends EventDispatcher {
  /** String marker identifying this concrete texture subtype. */
  readonly isTexture = true;

  /** Numeric identifier. */
  readonly id = textureId++;

  /** Stable texture identifier. */
  readonly uuid = globalThis.crypto.randomUUID();

  /** Display name. */
  name = "";

  /** Shared image data source. */
  source: Source;

  /** How UV coordinates map to this texture. */
  mapping = UV_MAPPING;

  /** UV attribute channel. */
  channel = 0;

  /** Horizontal UV wrapping mode. */
  wrapS: WrappingMode = Wrapping.ClampToEdge;

  /** Vertical UV wrapping mode. */
  wrapT: WrappingMode = Wrapping.ClampToEdge;

  /** Magnification selector; EASEL always samples nearest neighbours. */
  get magFilter(): number {
    return this.#magFilter;
  }

  /** Keeps magnification nearest-only on the CPU path. */
  set magFilter(value: number) {
    if (value !== DEFAULT_NEAREST_FILTER) {
      throw new RangeError("Texture.magFilter only supports nearest sampling.");
    }
    this.#magFilter = value;
  }

  /** Minification selector; EASEL never generates mipmaps. */
  get minFilter(): number {
    return this.#minFilter;
  }

  /** Keeps minification nearest-only on the CPU path. */
  set minFilter(value: number) {
    if (value !== DEFAULT_NEAREST_FILTER) {
      throw new RangeError("Texture.minFilter only supports nearest sampling.");
    }
    this.#minFilter = value;
  }

  /** Anisotropy is fixed to one by the CPU sampler. */
  get anisotropy(): number {
    return this.#anisotropy;
  }

  /** Keeps anisotropy disabled on the CPU path. */
  set anisotropy(value: number) {
    if (value !== DEFAULT_ANISOTROPY) {
      throw new RangeError(
        "Texture.anisotropy is fixed to one on the CPU path.",
      );
    }
    this.#anisotropy = value;
  }

  /** RGBA is the only format accepted by the packed CPU sampler. */
  get format(): number {
    return this.#format;
  }

  /** Rejects formats that require a different fragment layout. */
  set format(value: number) {
    if (value !== DEFAULT_RGBA_FORMAT) {
      throw new RangeError("Texture.format only supports packed RGBA pixels.");
    }
    this.#format = value;
  }

  /** Internal pixel formats are absent from the Canvas2D CPU path. */
  readonly internalFormat: undefined;

  /** Unsigned bytes are the CPU frame-buffer's fixed sample type. */
  get type(): number {
    return this.#type;
  }

  /** Rejects sample types that would add conversion work. */
  set type(value: number) {
    if (value !== DEFAULT_UNSIGNED_BYTE_TYPE) {
      throw new RangeError("Texture.type only supports unsigned-byte samples.");
    }
    this.#type = value;
  }

  /** UV offset. */
  offset = new Vector2();

  /** UV repeat. */
  repeat = new Vector2(1, 1);

  /** UV rotation center. */
  center = new Vector2();

  /** UV rotation in radians. */
  rotation = 0;

  /** Whether transformUv derives matrix from UV properties. */
  matrixAutoUpdate = true;

  /** UV transform matrix. */
  matrix = new Matrix3();

  /** Alpha remains straight because the rasterizer owns discrete compositing. */
  get premultiplyAlpha(): false {
    return false;
  }

  /** Rejects an extra texture-wide alpha conversion pass. */
  set premultiplyAlpha(value: boolean) {
    if (value) {
      throw new RangeError("Texture.premultiplyAlpha is fixed to false.");
    }
  }

  /** Whether to flip V coordinates. */
  flipY = true;

  /** Serialized row alignment for tightly packed RGBA inputs. */
  get unpackAlignment(): 1 | 4 {
    return this.#unpackAlignment;
  }

  /** Accepts the only row alignments used by image and raw RGBA sources. */
  set unpackAlignment(value: number) {
    if (value !== 1 && value !== 4) {
      throw new RangeError("Texture.unpackAlignment only supports 1 or 4.");
    }
    this.#unpackAlignment = value;
  }

  /** Texture bytes are sampled without an implicit color-space conversion. */
  get colorSpace(): "" {
    return DEFAULT_NO_COLOR_SPACE;
  }

  /** Rejects color conversions that would require another CPU pass. */
  set colorSpace(value: string) {
    if (value !== DEFAULT_NO_COLOR_SPACE) {
      throw new RangeError("Texture.colorSpace is fixed to no conversion.");
    }
  }

  /** Deprecated alias for {@link colorSpace}. */
  get encoding(): string {
    return this.colorSpace;
  }

  /** Delegates to {@link colorSpace}. */
  set encoding(value: string) {
    this.colorSpace = value;
  }

  /** User-owned serializable metadata. */
  userData: Record<string, unknown> = {};

  /** Number of requested texture updates. */
  version = 0;

  /** Optional callback invoked after a CPU update. */
  onUpdate: (() => void) | undefined = undefined;

  /** Packed unsigned-byte samples are never normalized to floats. */
  get normalized(): false {
    return false;
  }

  /** Rejects per-sample integer-to-float normalization. */
  set normalized(value: boolean) {
    if (value) {
      throw new RangeError("Texture.normalized is fixed to false.");
    }
  }

  #magFilter = DEFAULT_NEAREST_FILTER;
  #minFilter = DEFAULT_NEAREST_FILTER;
  #anisotropy = DEFAULT_ANISOTROPY;
  #format = DEFAULT_RGBA_FORMAT;
  #type = DEFAULT_UNSIGNED_BYTE_TYPE;
  #unpackAlignment: 1 | 4 = 4;
  #data: ImageData | undefined = undefined;
  #brightnessLevels: Uint8ClampedArray[] | undefined = undefined;
  #needsUpdate = false;

  /** Constructs a CPU-sampled texture around an optional image or pixel source. */
  constructor(
    image?: TextureImageSource,
    mapping: number = UV_MAPPING,
    wrapS: WrappingMode = Wrapping.ClampToEdge,
    wrapT: WrappingMode = Wrapping.ClampToEdge,
    magFilter: number = DEFAULT_NEAREST_FILTER,
    minFilter: number = DEFAULT_NEAREST_FILTER,
    format: number = DEFAULT_RGBA_FORMAT,
    type: number = DEFAULT_UNSIGNED_BYTE_TYPE,
    anisotropy: number = DEFAULT_ANISOTROPY,
    colorSpace: string = DEFAULT_NO_COLOR_SPACE,
  ) {
    super();
    this.source = new Source(image);
    this.mapping = mapping;
    this.wrapS = wrapS;
    this.wrapT = wrapT;
    this.magFilter = magFilter;
    this.minFilter = minFilter;
    this.format = format;
    this.type = type;
    this.anisotropy = anisotropy;
    this.colorSpace = colorSpace;
  }

  /** Current source image or raw pixel payload. */
  get image(): TextureImageSource {
    return this.source.data;
  }

  /** Replaces the source image without allocating a GPU resource. */
  set image(value: TextureImageSource) {
    this.source.data = value;
    this.#data = undefined;
    this.#brightnessLevels = undefined;
  }

  /** Whether the texture has pending CPU cache work. */
  get needsUpdate(): boolean {
    return this.#needsUpdate;
  }

  /** Marks or clears pending CPU cache work. */
  set needsUpdate(value: boolean) {
    this.#needsUpdate = value;
    if (value) {
      this.version++;
      this.source.needsUpdate = true;
    }
  }

  /** Explicitly clamps and caches the current image when dirty. */
  update(): this {
    if (!this.#needsUpdate) return this;
    this.#clampAndCache();
    this.#brightnessLevels = undefined;
    this.#needsUpdate = false;
    this.onUpdate?.();
    return this;
  }

  /** Cached pixel data, clamped to 128x128. */
  get data(): ImageData | undefined {
    return this.#data;
  }

  /** Pixel width, bounded by the CPU cache limit. */
  get width(): number {
    if (this.#data) return this.#data.width;
    return Math.min(MAX_SIZE, getDimension(this.image, "width"));
  }

  /** Pixel height, bounded by the CPU cache limit. */
  get height(): number {
    if (this.#data) return this.#data.height;
    return Math.min(MAX_SIZE, getDimension(this.image, "height"));
  }

  /** Pixel depth when the source declares one, otherwise zero. */
  get depth(): number {
    return getDimension(this.image, "depth");
  }

  /** Pre-multiplied brightness variants of cached pixel data. */
  get brightnessLevels(): Uint8ClampedArray[] | undefined {
    return this.#brightnessLevels;
  }

  /** Explicitly rebuilds brightness variants from cached data. */
  buildBrightnessLevels(): this {
    const imgData = this.data;
    if (!imgData) return this;
    const src = imgData.data;
    const levels: Uint8ClampedArray[] = new Array(TEXTURE_BRIGHTNESS_LEVELS);
    for (let level = 0; level < levels.length; level++) {
      const factor = (level + 1) / TEXTURE_BRIGHTNESS_LEVELS;
      const destination = new Uint8ClampedArray(src.length);
      for (let index = 0; index < src.length; index += 4) {
        destination[index] = (src[index] * factor + 0.5) | 0;
        destination[index + 1] = (src[index + 1] * factor + 0.5) | 0;
        destination[index + 2] = (src[index + 2] * factor + 0.5) | 0;
        destination[index + 3] = src[index + 3];
      }
      levels[level] = destination;
    }
    this.#brightnessLevels = levels;
    return this;
  }

  /** Updates the UV transform matrix from offset, repeat, rotation, and center. */
  updateMatrix(): void {
    this.matrix.setUvTransform(
      this.offset.x,
      this.offset.y,
      this.repeat.x,
      this.repeat.y,
      this.rotation,
      this.center.x,
      this.center.y,
    );
  }

  /** Returns an independent texture copy preserving the concrete class. */
  clone(): Texture {
    const Constructor = this.constructor as unknown as {
      new (image?: TextureImageSource): Texture;
    };
    let copy: Texture;
    try {
      copy = new Constructor(this.image);
    } catch {
      copy = new Texture(this.image);
    }
    return copy.copy(this);
  }

  /** Copies texture state and shares the source definition. */
  copy(source: Texture): this {
    this.name = source.name;
    this.source = source.source;
    this.mapping = source.mapping;
    this.channel = source.channel;
    this.wrapS = source.wrapS;
    this.wrapT = source.wrapT;
    this.magFilter = source.magFilter;
    this.minFilter = source.minFilter;
    this.anisotropy = source.anisotropy;
    this.format = source.format;
    this.type = source.type;
    this.normalized = source.normalized;
    this.offset.copy(source.offset);
    this.repeat.copy(source.repeat);
    this.center.copy(source.center);
    this.rotation = source.rotation;
    this.matrixAutoUpdate = source.matrixAutoUpdate;
    this.matrix.copy(source.matrix);
    this.premultiplyAlpha = source.premultiplyAlpha;
    this.flipY = source.flipY;
    this.unpackAlignment = source.unpackAlignment;
    this.colorSpace = source.colorSpace;
    this.userData = cloneUserData(source.userData);
    this.#data = cloneImageData(source.data);
    this.#brightnessLevels = source.brightnessLevels?.map(
      (level) => new Uint8ClampedArray(level),
    );
    this.needsUpdate = true;
    return this;
  }

  /** Sets known texture properties from a record; unknown values are ignored. */
  assign(values: Record<string, unknown>): this {
    for (const [key, nextValue] of Object.entries(values)) {
      if (nextValue === undefined) continue;
      if (!(key in this)) continue;
      const currentValue = (this as unknown as Record<string, unknown>)[key];
      if (copyMutableValue(currentValue, nextValue)) continue;
      try {
        (this as unknown as Record<string, unknown>)[key] = nextValue;
      } catch {
        // Read-only compatibility fields intentionally remain unchanged.
      }
    }
    return this;
  }

  /** Delegates to {@link assign} for three.js API parity. */
  setValues(values: Record<string, unknown>): this {
    return this.assign(values);
  }

  /** Serializes texture parameters and its source image. */
  toJSON(meta?: TextureSerializationMeta | string): TextureJSON {
    const isRoot = meta === undefined || typeof meta === "string";
    if (!isRoot && meta.textures[this.uuid] !== undefined) {
      return meta.textures[this.uuid];
    }

    const output: TextureJSON = {
      metadata: {
        version: 4.7,
        type: "Texture",
        generator: "Texture.toJSON",
      },
      uuid: this.uuid,
      name: this.name,
      image: this.source.toJSON(meta).uuid,
      mapping: this.mapping,
      channel: this.channel,
      repeat: [this.repeat.x, this.repeat.y],
      offset: [this.offset.x, this.offset.y],
      center: [this.center.x, this.center.y],
      rotation: this.rotation,
      wrap: [this.wrapS, this.wrapT],
      format: this.format,
      internalFormat: this.internalFormat,
      type: this.type,
      normalized: this.normalized,
      colorSpace: this.colorSpace,
      minFilter: this.minFilter,
      magFilter: this.magFilter,
      anisotropy: this.anisotropy,
      flipY: this.flipY,
      premultiplyAlpha: this.premultiplyAlpha,
      unpackAlignment: this.unpackAlignment,
    };
    if (Object.keys(this.userData).length > 0) {
      output.userData = cloneUserData(this.userData);
    }
    if (!isRoot) meta.textures[this.uuid] = output;
    return output;
  }

  /** Marks this texture as disposed and releases CPU caches. */
  dispose(): void {
    this.dispatchEvent({ type: "dispose" });
    this.image = undefined;
    this.#data = undefined;
    this.#brightnessLevels = undefined;
    this.#needsUpdate = false;
  }

  /** Applies matrix, wrapping, and vertical flip to a UV vector in place. */
  transformUv(uv: Vector2): Vector2 {
    if (this.mapping !== UV_MAPPING && this.mapping !== 0) return uv;
    if (this.matrixAutoUpdate) this.updateMatrix();
    const candidate = uv as Vector2 & {
      applyMatrix3?: (matrix: Matrix3) => unknown;
    };
    if (typeof candidate.applyMatrix3 === "function") {
      candidate.applyMatrix3(this.matrix);
    } else {
      const elements = this.matrix.elements;
      const x = candidate.x;
      const y = candidate.y;
      candidate.x = elements[0] * x + elements[3] * y + elements[6];
      candidate.y = elements[1] * x + elements[4] * y + elements[7];
    }
    uv.x = wrapCoordinate(uv.x, this.wrapS);
    uv.y = wrapCoordinate(uv.y, this.wrapT);
    if (this.flipY) uv.y = 1 - uv.y;
    return uv;
  }

  #clampAndCache(): void {
    const source = this.image;
    if (!source) return;

    if (isPixelSource(source)) {
      this.#data = clampPixelSource(source);
      return;
    }

    const sw = Math.max(0, Math.floor(getDimension(source, "width")));
    const sh = Math.max(0, Math.floor(getDimension(source, "height")));
    if (sw === 0 || sh === 0) return;

    const dw = Math.min(sw, MAX_SIZE);
    const dh = Math.min(sh, MAX_SIZE);
    let canvas: HTMLCanvasElement | OffscreenCanvas;
    if (typeof OffscreenCanvas !== "undefined") {
      canvas = new OffscreenCanvas(dw, dh);
    } else {
      if (typeof document === "undefined") return;
      canvas = document.createElement("canvas");
      canvas.width = dw;
      canvas.height = dh;
    }
    canvas.width = dw;
    canvas.height = dh;

    const context = canvas.getContext("2d") as
      | CanvasRenderingContext2D
      | OffscreenCanvasRenderingContext2D
      | null;
    if (!context) return;
    context.imageSmoothingEnabled = false;
    context.drawImage(source as CanvasImageSource, 0, 0, dw, dh);
    this.#data = context.getImageData(0, 0, dw, dh);
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function getDimension(
  source: unknown,
  name: "width" | "height" | "depth",
): number {
  if (!isRecord(source)) return 0;
  if (name === "width" && typeof source["videoWidth"] === "number") {
    return source["videoWidth"];
  }
  if (name === "height" && typeof source["videoHeight"] === "number") {
    return source["videoHeight"];
  }
  const value = source[name];
  return typeof value === "number" && Number.isFinite(value) && value > 0
    ? value
    : 0;
}

function isPixelSource(
  source: TextureImageSource,
): source is ImageDataLike<ImagePixelArray> {
  if (!isRecord(source)) return false;
  const data = source["data"];
  return (
    (data instanceof Uint8Array ||
      data instanceof Uint8ClampedArray ||
      data instanceof Float32Array) &&
    typeof source["width"] === "number" &&
    typeof source["height"] === "number"
  );
}

function clampPixelSource(source: ImageDataLike<ImagePixelArray>): ImageData {
  const width = Math.min(MAX_SIZE, Math.max(0, Math.floor(source.width)));
  const height = Math.min(MAX_SIZE, Math.max(0, Math.floor(source.height)));
  const pixels = new Uint8ClampedArray(width * height * 4);
  const sourceData = source.data;
  const sourceWidth = Math.max(0, Math.floor(source.width));
  for (let row = 0; row < height; row++) {
    const sourceOffset = row * sourceWidth * 4;
    const destinationOffset = row * width * 4;
    for (let column = 0; column < width * 4; column++) {
      pixels[destinationOffset + column] =
        sourceData[sourceOffset + column] ?? 0;
    }
  }
  return createImageData(pixels, width, height);
}

function createImageData(
  data: Uint8ClampedArray,
  width: number,
  height: number,
): ImageData {
  const ImageDataConstructor = globalThis.ImageData;
  if (ImageDataConstructor !== undefined) {
    return new ImageDataConstructor(
      data as Uint8ClampedArray<ArrayBuffer>,
      width,
      height,
    );
  }
  return { data, width, height, colorSpace: "srgb" } as ImageData;
}

function cloneImageData(data: ImageData | undefined): ImageData | undefined {
  if (!data) return;
  return createImageData(
    new Uint8ClampedArray(data.data),
    data.width,
    data.height,
  );
}

function cloneUserData(data: Record<string, unknown>): Record<string, unknown> {
  try {
    return JSON.parse(JSON.stringify(data)) as Record<string, unknown>;
  } catch {
    return {};
  }
}

function copyMutableValue(current: unknown, next: unknown): boolean {
  if (!(isRecord(current) && isRecord(next))) return false;
  const copy = current["copy"];
  if (typeof copy === "function") {
    copy.call(current, next);
    return true;
  }
  const x = next["x"];
  const y = next["y"];
  if (typeof x === "number" && typeof y === "number") {
    const set = current["set"];
    if (typeof set === "function") {
      set.call(current, x, y);
      return true;
    }
  }
  return false;
}

function wrapCoordinate(value: number, mode: number): number {
  if (value >= 0 && value <= 1) return value;
  if (mode === Wrapping.Repeat || mode === 1000) {
    return value - Math.floor(value);
  }
  if (mode === Wrapping.MirroredRepeat || mode === 1002) {
    const floor = Math.floor(value);
    return Math.abs(floor % 2) === 1 ? Math.ceil(value) - value : value - floor;
  }
  return value < 0 ? 0 : 1;
}
