import type { ExampleRegistryEntry } from "../loaders/examples.ts";

// Generated by `bun run examples:registry` from each example's own meta and
// controls, in three.js r186 examples/files.json order of meta.upstream.
// Do not edit by hand.
export const categoryLabels = {
  canvas: "canvas",
  webaudio: "webaudio",
  misc: "misc",
} as const;

export const examples: ExampleRegistryEntry[] = [
  {
    meta: {
      id: "canvas_geometry_colors",
      upstream: "webgl_geometry_colors",
      name: "geometry / colors",
      category: "canvas",
      animated: true,
      description:
        "Three flat-shaded icosahedra with hue, saturation and red-to-yellow vertex color gradients and black wireframe overlays float above soft canvas-texture shadows while the camera follows the pointer.",
      differences: [
        "MeshPhongMaterial with shininess 0 becomes an EASEL LambertMaterial with flat baked lighting, which has no specular term; with shininess 0 the Phong highlight is a faint uniform sheen that the port drops.",
        "EASEL's Color.setRGB rejects components outside 0 to 1, so the third icosahedron's green channel is clamped at 0 before it is stored; three.js stores the negative value and clamps at output, which only changes the gradient on the top faces slightly.",
        "EASEL lights each vertex in linear space and encodes it to sRGB before interpolating across the face, where three.js interpolates in linear space and encodes per pixel, so the gradients blend slightly darker between vertices.",
        "The black wireframe overlay shares the faces' depth, so EASEL's depth test hides short stretches of some edges where three.js draws them unbroken.",
        "The upstream page follows the mouse over the whole window; the embedded stage follows the pointer over its canvas, measured from the canvas center.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_geometry_colors/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_geometry_colors/three.js")).example,
  },
  {
    meta: {
      id: "canvas_geometry_convex",
      upstream: "webgl_geometry_convex",
      name: "geometry / convex",
      category: "canvas",
      animated: true,
      description:
        "A translucent convex hull built around the twenty vertices of a dodecahedron spins beside an axes helper, with the source vertices drawn as blue points and orbit controls for the camera.",
      differences: [
        "EASEL points are filled discs with an integer pixel radius and no texture sampling, alphaTest or size attenuation, so solid blue discs of radius 2 stand in for the disc.png sprites whose size shrinks with distance.",
        "The hull's opacity 0.5 maps to EASEL's discrete opacity level 4 of 8, so the hull blends through one of nine fixed translucency steps (here exactly half) rather than a continuous alpha.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_geometry_convex/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_geometry_convex/three.js")).example,
  },
  {
    meta: {
      id: "canvas_geometry_cube",
      upstream: "webgl_geometry_cube",
      name: "geometry / cube",
      category: "canvas",
      animated: true,
      description:
        "A unit box textured with the wooden crate GIF tumbles slowly around its X and Y axes.",
      differences: [
        "EASEL caches the 256x256 crate.gif at 128x128 and samples it nearest-neighbor with affine warping, so the wood grain is blockier and bends across each face instead of being filtered and perspective-correct.",
        "EASEL's TextureLoader.load returns nothing, so the port assigns the map in the load callback, where it also sets colorSpace and re-caches the already decoded texels with update(); the cube draws untextured white for the first frames, before the data-URL GIF is decoded.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_geometry_cube/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_geometry_cube/three.js")).example,
  },
  {
    meta: {
      id: "canvas_interactive_buffergeometry",
      upstream: "webgl_interactive_buffergeometry",
      name: "interactive / buffergeometry",
      category: "canvas",
      animated: true,
      description:
        "Five thousand randomly placed, vertex-colored triangles in one rotating Geometry are raycast every frame, and a white outline traces the triangle under the pointer.",
      differences: [
        "EASEL has no MeshPhongMaterial, so the triangles use LambertMaterial and lose the white specular highlights (shininess 250) of the three.js original.",
        "EASEL bakes lighting per vertex and rasterizes the triangles and the outline on the CPU without anti-aliasing, so edges are jagged where the three.js renderer enables antialias.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_interactive_buffergeometry/easel.js"))
        .example,
    loadThree: async () =>
      (await import("./canvas/canvas_interactive_buffergeometry/three.js"))
        .example,
  },
  {
    meta: {
      id: "canvas_interactive_cubes",
      upstream: "webgl_interactive_cubes",
      name: "interactive / cubes",
      category: "canvas",
      animated: true,
      description:
        "Two thousand randomly colored, rotated, and scaled Lambert cubes are raycast every frame while the camera slowly orbits, and the cube under the pointer turns red.",
      differences: [
        "EASEL bakes Lambert lighting per vertex (Gouraud) instead of per fragment, and it rasterizes the cubes on the CPU without anti-aliasing, so cube edges are jagged where the three.js renderer enables antialias.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_interactive_cubes/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_interactive_cubes/three.js")).example,
  },
  {
    meta: {
      id: "canvas_interactive_cubes_ortho",
      upstream: "webgl_interactive_cubes_ortho",
      name: "interactive / cubes / ortho",
      category: "canvas",
      animated: true,
      description:
        "Two thousand randomly colored, rotated, and scaled Lambert cubes are viewed through an orthographic camera that slowly orbits them, and the cube picked by an orthographic raycast under the pointer turns red.",
      differences: [
        "EASEL bakes Lambert lighting per vertex (Gouraud) instead of per fragment, and it rasterizes the cubes on the CPU without anti-aliasing, so cube edges are jagged where the three.js renderer enables antialias.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_interactive_cubes_ortho/easel.js"))
        .example,
    loadThree: async () =>
      (await import("./canvas/canvas_interactive_cubes_ortho/three.js"))
        .example,
  },
  {
    meta: {
      id: "canvas_interactive_lines",
      upstream: "webgl_interactive_lines",
      name: "interactive / lines",
      category: "canvas",
      animated: true,
      description:
        "Fifty randomly colored Line and LineSegments copies of one random walk, nested under a random parent transform, are raycast every frame so a red sphere marks the line under the pointer while the camera slowly orbits.",
      differences: [
        "The three.js renderer enables antialias; EASEL rasterizes the lines and the red marker sphere on the CPU without anti-aliasing, so their edges are jagged.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_interactive_lines/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_interactive_lines/three.js")).example,
  },
  {
    meta: {
      id: "canvas_interactive_raycasting_points",
      upstream: "webgl_interactive_raycasting_points",
      name: "interactive / raycasting / points",
      category: "canvas",
      animated: true,
      description:
        "Three 12,800-point clouds (non-indexed, indexed, and indexed with a draw group) circle past the camera while the pointer raycasts them and drops shrinking red spheres at each hit.",
      differences: [
        "EASEL point size is an integer pixel radius without size attenuation, so the 0.05-unit points (under one pixel wide in three.js at this size) become 1-pixel-radius discs, about 3 pixels wide, that do not scale with distance.",
        "EASEL Geometry has no addGroup, so the third cloud is indexed like the second and skips the draw-group call.",
        "Points and spheres are rasterized on the CPU without anti-aliasing.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_interactive_raycasting_points/easel.js"))
        .example,
    loadThree: async () =>
      (await import("./canvas/canvas_interactive_raycasting_points/three.js"))
        .example,
  },
  {
    meta: {
      id: "canvas_interactive_voxelpainter",
      upstream: "webgl_interactive_voxelpainter",
      name: "interactive / voxelpainter",
      category: "canvas",
      animated: true,
      description:
        "Click the grid to stack textured orange voxels where a translucent red roll-over cube snaps to the picked face; Shift-click removes a voxel.",
      differences: [
        "The upstream page tracks Shift with document keydown and keyup listeners; both ports read shiftKey from the pointerdown event so every listener stays on the canvas.",
        "EASEL's TextureLoader.load returns nothing, so the port assigns the square-outline map in the load callback, where it also sets colorSpace and re-caches the already decoded texels with update(); voxels placed before the data-URL PNG is decoded draw untextured until it arrives.",
        "The 16x16 square-outline texture is sampled nearest-neighbor with affine warping instead of being filtered and perspective-correct.",
        "EASEL has discrete opacity levels, so the roll-over cube's 0.5 opacity becomes level 4 of 8.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_interactive_voxelpainter/easel.js"))
        .example,
    loadThree: async () =>
      (await import("./canvas/canvas_interactive_voxelpainter/three.js"))
        .example,
  },
  {
    meta: {
      id: "canvas_loader_bvh",
      upstream: "webgl_loader_bvh",
      name: "loader / bvh",
      category: "canvas",
      animated: true,
      description:
        "Parse a Biovision Hierarchy motion file with BVHLoader and play its skeleton animation through an Animator, drawn by a SkeletonHelper over a grid.",
      differences: [
        "The upstream pirouette.bvh has no licence notice and credits the CMU motion capture database, whose terms are not an open licence, and its rig does not match the CMU skeleton, so both sides load spin.bvh instead: a 19-joint humanoid pirouette with 90 frames at 30 fps authored for this repository, in place of 43 joints and 592 frames at 120 fps.",
        "EASEL SkeletonHelper reads prepared world matrices and does not update itself, so the port updates the bone hierarchy's world matrices and calls skeletonHelper.update() after each animator step.",
        "Helper lines are drawn one pixel wide without antialiasing.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_loader_bvh/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_loader_bvh/three.js")).example,
  },
  {
    meta: {
      id: "canvas_loader_gcode",
      upstream: "webgl_loader_gcode",
      name: "loader / gcode",
      category: "canvas",
      animated: true,
      description:
        "Parse 3D-printer G-code with GCodeLoader and draw extrusion and travel moves as colored line segments.",
      differences: [
        "The default asset is test_m82 and the asset selector offers only test_m82 and test_m83; benchy.gcode (3DBenchy) is omitted because its license is unclear.",
      ],
    },
    controls: [
      {
        type: "select",
        key: "asset",
        label: "asset",
        options: ["test_m82", "test_m83"],
        default: "test_m82",
      },
    ],
    load: async () =>
      (await import("./canvas/canvas_loader_gcode/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_loader_gcode/three.js")).example,
  },
  {
    meta: {
      id: "canvas_loader_imagebitmap",
      upstream: "webgl_loader_imagebitmap",
      name: "loader / imagebitmap",
      category: "canvas",
      animated: true,
      description:
        "Six cubes appear one by one over a rotating grid, three textured through ImageLoader with a red tint and three through ImageBitmapLoader.",
      differences: [
        "Both sides texture the cubes with the checked-in crate.gif instead of earth_atmos_2048.jpg, whose license is unknown, and load it from a data URL without the cache-busting query string.",
        "EASEL's CanvasTexture accepts only a canvas, so the port wraps the HTMLImageElement and the ImageBitmap in a plain Texture and caches it explicitly with needsUpdate and update(), because the EASEL renderer does not refresh textures on its own.",
        "EASEL applies flipY to ImageBitmap sources, unlike WebGL, so the bitmap textures set flipY to false to undo the imageOrientation 'flipY' decode and stay upright like the image textures.",
        "EASEL calls Texture.onUpdate with no argument, so the ImageBitmap is closed through a closure instead of texture.source.data.",
        "EASEL caches the 256x256 crate at 128x128 and samples it nearest-neighbor with affine warping, so the grain is blockier and bends across each face.",
        "Cube positions and rotations are random, so the two sides place their cubes differently.",
        "Edges are aliased because EASEL has no antialiasing.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_loader_imagebitmap/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_loader_imagebitmap/three.js")).example,
  },
  {
    meta: {
      id: "canvas_loader_nrrd",
      upstream: "webgl_loader_nrrd",
      name: "loader / nrrd",
      category: "canvas",
      animated: true,
      description:
        "Load an NRRD scalar volume and show three orthogonal slices inside its bounding box, with index, threshold, and window sliders.",
      differences: [
        "The volume is stent.nrrd (public domain) instead of I.nrrd, whose license is unknown; the slider ranges come from stent.nrrd, whose samples run from 0 to 1, so the threshold and window sliders with upstream's step of 1 only toggle between 0 and 1.",
        "EASEL's NRRDLoader cannot decode gzip payloads, so the EASEL side inflates the same stent.nrrd bytes with DecompressionStream and parses the result as raw data; the bounding box, which needs only the header, draws on the first frame and the slices appear a moment later.",
        "EASEL has no Volume.extractSlice or VolumeSlice, so the example repaints each slice itself from NRRDVolume.data into a DataTexture on a PlaneGeometry, using three.js's threshold and window formulas, and only when a slider changes.",
        "EASEL textures are capped at 128x128 texels, so the 256-sample edges of the x and y slices are sampled nearest-neighbor at half resolution.",
      ],
    },
    controls: [
      {
        type: "slider",
        key: "indexX",
        label: "indexX",
        min: 0,
        max: 128,
        step: 1,
        default: 64,
      },
      {
        type: "slider",
        key: "indexY",
        label: "indexY",
        min: 0,
        max: 128,
        step: 1,
        default: 64,
      },
      {
        type: "slider",
        key: "indexZ",
        label: "indexZ",
        min: 0,
        max: 256,
        step: 1,
        default: 64,
      },
      {
        type: "slider",
        key: "lowerThreshold",
        label: "Lower Threshold",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
      },
      {
        type: "slider",
        key: "upperThreshold",
        label: "Upper Threshold",
        min: 0,
        max: 1,
        step: 1,
        default: 1,
      },
      {
        type: "slider",
        key: "windowLow",
        label: "Window Low",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
      },
      {
        type: "slider",
        key: "windowHigh",
        label: "Window High",
        min: 0,
        max: 1,
        step: 1,
        default: 1,
      },
    ],
    load: async () =>
      (await import("./canvas/canvas_loader_nrrd/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_loader_nrrd/three.js")).example,
  },
  {
    meta: {
      id: "canvas_loader_obj",
      upstream: "webgl_loader_obj",
      name: "loader / obj",
      category: "canvas",
      animated: true,
      description:
        "Parse a Wavefront OBJ model with OBJLoader, light it from the camera with a point light, and orbit it with damping.",
      differences: [
        "Both sides load the CC0 Suzanne OBJ instead of the unlicensed male02 model, so there is no MTL file and no texture; the scale is 0.8 and position.y is 0 instead of 0.01 and -0.95 so Suzanne fills the view about as much as male02 does.",
        "three.js falls back to a white MeshPhongMaterial when no MTL is set; EASEL has no Phong material and its OBJLoader falls back to an unlit BasicMaterial, so the port passes a white LambertMaterial for the Suzanne usemtl group through setMaterials and has no specular highlight.",
        "Lighting is baked per vertex (Gouraud) instead of per pixel.",
        "Edges are aliased because EASEL has no antialiasing.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_loader_obj/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_loader_obj/three.js")).example,
  },
  {
    meta: {
      id: "canvas_loader_pcd",
      upstream: "webgl_loader_pcd",
      name: "loader / pcd",
      category: "canvas",
      animated: true,
      description:
        "Load a Point Cloud Data file with PCDLoader, center it, and orbit around its colored points.",
      differences: [
        "The default file is ascii/simple.pcd instead of binary/Zaghetto.pcd because EASEL's PCDLoader only parses ASCII PCD data.",
        "The type selector is omitted; binary/Zaghetto.pcd, binary/Zaghetto_8bit.pcd, and binary_compressed/pcl_logo.pcd are binary PCD files that EASEL's PCDLoader cannot parse.",
        "EASEL point size is an integer pixel radius, so the size slider is converted to a radius from the camera distance once per frame and clamps to at least one pixel; all points share that radius instead of attenuating individually.",
      ],
    },
    controls: [
      {
        type: "slider",
        key: "size",
        label: "size",
        min: 0.001,
        max: 0.01,
        step: 0.001,
        default: 0.005,
      },
      {
        type: "color",
        key: "color",
        label: "color",
        default: "#ffffff",
      },
    ],
    load: async () =>
      (await import("./canvas/canvas_loader_pcd/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_loader_pcd/three.js")).example,
  },
  {
    meta: {
      id: "canvas_loader_svg",
      upstream: "webgl_loader_svg",
      name: "loader / svg",
      category: "canvas",
      animated: true,
      description:
        "Parse SVG files into ShapeGeometry fills and stroke meshes over a grid, with toggles for strokes, fills and wireframes.",
      differences: [
        "The default file is Joins and caps instead of Tiger, and the Tiger, emoji, blueprint, Defs, Defs2, Defs3, Defs4 and Defs5 files are left out: tiger.svg is the Ghostscript tiger (AGPL-3.0), emoji.svg is a Noto Emoji glyph, blueprint.svg is a third-party Illustrator file with no stated license, and tests/testDefs/* are CC-BY-SA 2.5.",
        "EASEL's SVGLoader has no createFillMaterial, createStrokeMaterial or pointsToStroke, so the port builds BasicMaterials from each path's style (fill defaults to black, stroke width to 1) and draws each stroke segment as a plain quad, without line joins, caps or miter limits.",
        "EASEL's SVGLoader ignores <style> sheets, CSS classes, <use>/<defs> references, gradients and non-px units, so Style CSS inside defs, Multiple CSS classes, Styles in svg tag and Units draw with default black fills, and gradient fills fall back to a flat color.",
        "EASEL's SVG path parser reads the implicit line-to pairs after an absolute M command as relative from the second pair on, so paths written as M x,y x,y x,y (the Joins and caps shapes, among others) draw distorted.",
        "EASEL's SVG path parser rejects arc commands whose flags are packed against the next number (for example A4.679 4.679 0 0012.711.092), so Test 9 shows only the grid.",
        "SVG opacity is rounded to EASEL's 9 discrete opacity levels, and draw order follows material.layer because EASEL has no per-mesh renderOrder.",
      ],
    },
    controls: [
      {
        type: "select",
        key: "currentURL",
        label: "SVG File",
        options: [
          "Joins and caps",
          "Hexagon",
          "Energy",
          "Test 1",
          "Test 2",
          "Test 3",
          "Test 4",
          "Test 5",
          "Test 6",
          "Test 7",
          "Test 8",
          "Test 9",
          "Units",
          "Ordering",
          "Style CSS inside defs",
          "Styled Paths",
          "Multiple CSS classes",
          "Zero Radius",
          "Styles in svg tag",
          "Round join",
          "Ellipse Transformations",
          "singlePointTest",
          "singlePointTest2",
          "singlePointTest3",
          "emptyPath",
          "wideStroke",
          "letter",
        ],
        default: "Joins and caps",
      },
      {
        type: "select",
        key: "drawStrokes",
        label: "Draw strokes",
        options: ["on", "off"],
        default: "on",
      },
      {
        type: "select",
        key: "drawFillShapes",
        label: "Draw fill shapes",
        options: ["on", "off"],
        default: "on",
      },
      {
        type: "select",
        key: "strokesWireframe",
        label: "Wireframe strokes",
        options: ["on", "off"],
        default: "off",
      },
      {
        type: "select",
        key: "fillShapesWireframe",
        label: "Wireframe fill shapes",
        options: ["on", "off"],
        default: "off",
      },
    ],
    load: async () =>
      (await import("./canvas/canvas_loader_svg/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_loader_svg/three.js")).example,
  },
  {
    meta: {
      id: "canvas_loader_texture_tga",
      upstream: "webgl_loader_texture_tga",
      name: "loader / texture / tga",
      category: "canvas",
      animated: true,
      description:
        "Two lit crates side by side, textured with a greyscale and a color-mapped TGA image decoded by TGALoader, with orbit controls.",
      differences: [
        "MeshPhongMaterial becomes LambertMaterial because EASEL has no Phong shading, so the crates show no specular highlight.",
        "EASEL has no createDataTexture on DataTextureLoader, so the port wraps TGALoader.parse output in a DataTexture and builds its brightness levels, as EASEL's DataTextureLoader.load does.",
        "EASEL caches the 256x256 TGA images at 128x128 and samples them nearest-neighbor with affine warping, so the wood grain is blockier and bends across each face.",
        "Edges are aliased because EASEL has no antialiasing.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_loader_texture_tga/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_loader_texture_tga/three.js")).example,
  },
  {
    meta: {
      id: "canvas_loader_vox",
      upstream: "webgl_loader_vox",
      name: "loader / vox",
      category: "canvas",
      animated: true,
      description:
        "Parse a MagicaVoxel monument with VOXLoader, light it with hemisphere and directional lights, and orbit it.",
      differences: [
        "EASEL VOXLoader builds a vertex-colored LambertMaterial mesh with per-vertex baked lighting instead of the per-pixel MeshStandardMaterial that three.js builds.",
        "EASEL lights in display color space without the linear-to-sRGB output conversion, so mid-tones differ slightly.",
        "Edges are aliased because EASEL has no antialiasing.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_loader_vox/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_loader_vox/three.js")).example,
  },
  {
    meta: {
      id: "canvas_loader_xyz",
      upstream: "webgl_loader_xyz",
      name: "loader / xyz",
      category: "canvas",
      animated: true,
      description:
        "Parse an XYZ point-cloud helix with XYZLoader and spin it as a centered Points object.",
      differences: [
        "EASEL PointsMaterial.size is an integer pixel radius without distance attenuation, so the 0.1 world-unit point size becomes a fixed 1-pixel radius.",
        "Points are drawn as aliased square pixels because EASEL has no antialiasing.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_loader_xyz/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_loader_xyz/three.js")).example,
  },
  {
    meta: {
      id: "canvas_lod",
      upstream: "webgl_lod",
      name: "lod",
      category: "canvas",
      animated: true,
      description:
        "Fly through 1000 wireframe icosahedra whose LOD objects swap between five detail levels by camera distance.",
      differences: [
        "EASEL's IcosahedronGeometry reads detail as 4^detail recursive splits, so the port builds the five icosahedra with three.js's (detail + 1)^2 subdivision in the example itself; the vertex positions match three.js.",
        "EASEL draws wireframe edges as 1-pixel aliased lines in each triangle's flat-shaded color, so the material uses Shading.Flat to get lit at all; the red point light and white directional light shade each face uniformly instead of per fragment.",
        "EASEL does not apply fog to wireframe edges, so distant icosahedra stay at full brightness instead of fading to black toward the 15000-unit fog far distance.",
      ],
    },
    controls: [],
    load: async () => (await import("./canvas/canvas_lod/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_lod/three.js")).example,
  },
  {
    meta: {
      id: "canvas_materials_texture_canvas",
      upstream: "webgl_materials_texture_canvas",
      name: "materials / texture / canvas",
      category: "canvas",
      animated: true,
      description:
        "Click and draw in the white box to paint a 2D canvas that textures a rotating cube through a CanvasTexture.",
      differences: [
        "EASEL textures are cached at no more than 128x128 texels and sampled nearest-neighbor; the 128x128 drawing canvas fits that limit exactly, but strokes look blocky and warp affinely on the cube instead of being filtered and perspective-correct.",
        "EASEL copies the drawing canvas into its texture cache only when texture.update() runs, so the port calls update() once per frame after needsUpdate is set, where three.js re-uploads the canvas on its own.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_materials_texture_canvas/easel.js"))
        .example,
    loadThree: async () =>
      (await import("./canvas/canvas_materials_texture_canvas/three.js"))
        .example,
  },
  {
    meta: {
      id: "canvas_materials_video_webcam",
      upstream: "webgl_materials_video_webcam",
      name: "materials / video / webcam",
      category: "canvas",
      animated: true,
      description:
        "Click the canvas to stream the webcam onto 128 planes arranged on a sphere around the camera, then drag to look around.",
      differences: [
        "Both sides request the camera on the first click on their own canvas instead of at page load, so the side-by-side page never prompts on its own; each side opens its own stream.",
        "EASEL caches each video frame at 128x128 and samples it nearest-neighbor with affine warping, so the webcam image is much blockier than the filtered three.js texture.",
        "EASEL re-reads the video only when texture.update() runs, so the port calls it once per frame, where three.js refreshes the VideoTexture on its own.",
        "Before a stream arrives, three.js samples an empty texture and draws the planes black on the black background, while EASEL draws them in the material's white base colour until the first video frame is cached.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_materials_video_webcam/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_materials_video_webcam/three.js")).example,
  },
  {
    meta: {
      id: "canvas_math_obb",
      upstream: "webgl_math_obb",
      name: "math / obb",
      category: "canvas",
      animated: true,
      description:
        "One hundred rotating boxes test oriented bounding boxes against each other every frame, turning red on collision; click a box to pick it with an OBB ray test.",
      differences: [
        "EASEL bakes Lambert and hemisphere lighting per vertex on the CPU, so box faces show flat shading instead of per-pixel lighting.",
        "With the upstream hemisphere intensity of 4, EASEL's vertex lighting saturates nearly every face to full green or red, so the boxes look flatter than in three.js, where faces turned toward the ground color stay darker.",
        "The black wireframe hitbox is drawn with EASEL's CPU wireframe rasterizer without anti-aliasing.",
        "Both sides place, rotate, and scale the boxes with Math.random as upstream does, so the two canvases show different layouts and collisions.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_math_obb/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_math_obb/three.js")).example,
  },
  {
    meta: {
      id: "canvas_math_orientation_transform",
      upstream: "webgl_math_orientation_transform",
      name: "math / orientation / transform",
      category: "canvas",
      animated: true,
      description:
        "A cone turns toward a red target that jumps to a random point on a wireframe sphere every two seconds, using Quaternion.rotateTowards or an instant lookAt.",
      differences: [
        "EASEL has no MeshNormalMaterial, so the cone uses a BasicMaterial whose vertex colors are recomputed each frame from its view-space vertex normals and interpolated across each face instead of per pixel.",
        "The wireframe sphere's opacity 0.3 becomes EASEL opacity level 6 of 8, blended in EASEL's quantized color space, so single lines draw at about 89 gray on black where three.js gives about 61.",
        "The lil-gui useLookAt checkbox becomes a select control with on and off options.",
      ],
    },
    controls: [
      {
        type: "select",
        key: "useLookAt",
        label: "useLookAt",
        options: ["on", "off"],
        default: "off",
      },
    ],
    load: async () =>
      (await import("./canvas/canvas_math_orientation_transform/easel.js"))
        .example,
    loadThree: async () =>
      (await import("./canvas/canvas_math_orientation_transform/three.js"))
        .example,
  },
  {
    meta: {
      id: "canvas_morphtargets_sphere",
      upstream: "webgl_morphtargets_sphere",
      name: "morphtargets / sphere",
      category: "canvas",
      animated: true,
      description:
        "A glTF sphere lit by red and green point lights spins while its blob morph target swings back and forth, with white point sprites following the morphed vertices.",
      differences: [
        "EASEL's GLTFLoader does not read morph targets and its renderer ignores morphTargetInfluences, so the port reads the two POSITION and NORMAL morph deltas from the same glTF buffer and blends them into the shared geometry on the CPU each frame.",
        "EASEL does not keep a node's Euler rotation in sync when its quaternion is changed in place, so the port copies the glTF node quaternion into mesh.rotation before applying the upstream rotation.z change.",
        "The glTF PBR material is loaded as an EASEL Lambert material with CPU-baked vertex lighting, so the sphere has no specular response.",
        "EASEL points are filled discs with an integer pixel radius and no texture sampling or alphaTest, so solid discs of radius 5 (11 pixels across) stand in for the 10-pixel disc.png sprites.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_morphtargets_sphere/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_morphtargets_sphere/three.js")).example,
  },
  {
    meta: {
      id: "canvas_panorama_equirectangular",
      upstream: "webgl_panorama_equirectangular",
      name: "panorama / equirectangular",
      category: "canvas",
      animated: true,
      description:
        "An equirectangular panorama mapped inside an inverted sphere; the view pans slowly, drag to look around and scroll to zoom.",
      differences: [
        "Both sides show Greg Zaal's CC0 Poly Haven panorama spruit_sunrise_2k.hdr.jpg from the three.js repository instead of 2294472375_24a3b8ef46_o.jpg, whose license is unknown.",
        "EASEL caches the 2048x1024 panorama at 128x128 and samples it nearest-neighbor with affine warping, so the full-screen view is very blocky and bends across each sphere face instead of being filtered and perspective-correct.",
        "EASEL's TextureLoader.load returns nothing, so the port assigns the map in the load callback, where it also sets colorSpace and re-caches the already decoded texels with update(); the sphere draws untextured white until the data-URL JPEG is decoded.",
        "Pointer move, pointer up and wheel listeners are attached to the canvas, with pointer capture, instead of the document, so dragging and zooming only start over the example.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_panorama_equirectangular/easel.js"))
        .example,
    loadThree: async () =>
      (await import("./canvas/canvas_panorama_equirectangular/three.js"))
        .example,
  },
  {
    meta: {
      id: "canvas_points_billboards",
      upstream: "webgl_points_billboards",
      name: "points / billboards",
      category: "canvas",
      animated: true,
      description:
        "Ten thousand randomly placed point billboards cycle through hues in exponential fog while the camera follows the pointer.",
      differences: [
        "EASEL points are filled discs with an integer pixel radius and no texture sampling or alphaTest, so solid discs stand in for the alpha-tested disc.png sprites, and disc.png is not loaded.",
        "EASEL PointsMaterial has no sizeAttenuation, so with the toggle on every point uses one radius, taken from the three.js size-35 formula at the 1000-unit camera distance (3 pixels at 640x360), instead of growing as it comes closer; with the toggle off the radius is 18 pixels, matching the 35-pixel sprites.",
      ],
    },
    controls: [
      {
        type: "select",
        key: "sizeAttenuation",
        label: "sizeAttenuation",
        options: ["on", "off"],
        default: "on",
      },
    ],
    load: async () =>
      (await import("./canvas/canvas_points_billboards/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_points_billboards/three.js")).example,
  },
  {
    meta: {
      id: "canvas_raycaster_sprite",
      upstream: "webgl_raycaster_sprite",
      name: "raycaster / sprite",
      category: "canvas",
      animated: true,
      description:
        "Hover the pointer over rotated, offset, and nested sprites to pick them with a Raycaster.",
      differences: [
        "EASEL sprites have no sizeAttenuation option, so the small sprite scales with distance instead of keeping a fixed screen size.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_raycaster_sprite/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_raycaster_sprite/three.js")).example,
  },
  {
    meta: {
      id: "canvas_test_memory",
      upstream: "webgl_test_memory",
      name: "test / memory",
      category: "canvas",
      animated: true,
      description:
        "Create, render, and dispose a new random wireframe sphere, material, and solid-color texture every frame to exercise resource cleanup.",
      differences: [
        "EASEL wireframe lines ignore material.map and draw in material.color, so the port also sets the material color to the random texture color; otherwise the white lines would vanish on the white background.",
        "Each frame's texture is a 128 x 128 DataTexture filled with the random color instead of a 256 x 256 CanvasTexture, because EASEL clamps textures to 128 texels and the example must run without a DOM document.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_test_memory/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_test_memory/three.js")).example,
  },
  {
    meta: {
      id: "canvas_video_panorama_equirectangular",
      upstream: "webgl_video_panorama_equirectangular",
      name: "video / panorama / equirectangular",
      category: "canvas",
      animated: true,
      description:
        "An animated equirectangular panorama is mapped onto the inside of an inverted sphere; drag to look around from its centre.",
      differences: [
        "textures/pano.webm and pano.mp4 carry no licence notice, so both sides substitute a generated 512x256 equirectangular canvas animation (sky, ground, a circling sun and pillars every 30 degrees) drawn each frame and used as a CanvasTexture instead of a VideoTexture.",
        "EASEL caches the panorama at 128x128 and samples it nearest-neighbor with affine warping, so the surroundings are blocky and bend across the 60x40 sphere's faces instead of being filtered and perspective-correct.",
        "EASEL re-reads the canvas only on an explicit texture.update() after needsUpdate is set, so the port does both every frame.",
        "Pointer listeners are on the canvas with pointer capture instead of on the document, so drags start only on the example.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_video_panorama_equirectangular/easel.js"))
        .example,
    loadThree: async () =>
      (await import("./canvas/canvas_video_panorama_equirectangular/three.js"))
        .example,
  },
  {
    meta: {
      id: "canvas_buffergeometry",
      upstream: "webgl_buffergeometry",
      name: "buffergeometry",
      category: "canvas",
      animated: true,
      description:
        "160,000 random non-indexed triangles with flat face normals and position-based vertex colors fill a fogged cube that tumbles under ambient and directional light.",
      differences: [
        "MeshPhongMaterial becomes LambertMaterial with Gouraud (per-vertex) lighting, so the triangles have no white specular highlight (specular 0xffffff, shininess 250).",
        "EASEL only reads RGB (itemSize 3) vertex colors and has no per-vertex alpha, so the random per-triangle alpha is dropped and the material is opaque instead of transparent; transparent: true would also turn off depth writes in EASEL and draw the triangles in submission order.",
        "Attribute.onUpload is a GPU upload hook with no EASEL equivalent, so the typed arrays stay in memory.",
        "Fog is sampled once per vertex from EASEL's 256-entry fog table instead of per pixel.",
        "All 160,000 triangles are transformed, lit and rasterized on the CPU every frame; a Bun stub-canvas run at 640x360 measured a median of about 62 ms per frame (roughly 16 fps), above the 33 ms budget, and the count is kept to match three.js.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_buffergeometry/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_buffergeometry/three.js")).example,
  },
  {
    meta: {
      id: "canvas_buffergeometry_drawrange",
      upstream: "webgl_buffergeometry_drawrange",
      name: "buffergeometry / drawrange",
      category: "canvas",
      animated: true,
      description:
        "Up to 1,000 particles drift inside a rotating box and connect with fading line segments when they come close, using setDrawRange to draw only the live part of preallocated point and line buffers.",
      differences: [
        "EASEL has no blending modes, so the additive blending on the points, the connecting lines and the box outline becomes a plain overwrite: overlapping lines no longer add up to brighter crossings, and the points material uses layer 1 so the white dots stay on top of the lines that end on them.",
        "EASEL point size is an integer pixel radius without size attenuation, so size 3 (a 3-pixel-wide square that ignores distance in three.js) becomes a radius-1 disc about 3 pixels wide.",
        "Attribute.setUsage(DynamicDrawUsage) is a GPU buffer hint with no EASEL equivalent and is dropped; the attributes are republished with needsUpdate each frame as in three.js.",
        "Points and lines are rasterized on the CPU without anti-aliasing, and lines are 1 pixel wide.",
        "The particle update, the O(n^2) connection search and all drawn points and lines run on the CPU; a Bun stub-canvas run at 640x360 measured a median of about 7 to 16 ms per frame at the defaults and about 85 ms per frame with particleCount 1000 and minDistance 300.",
      ],
    },
    controls: [
      {
        type: "select",
        key: "showDots",
        label: "showDots",
        options: ["on", "off"],
        default: "on",
      },
      {
        type: "select",
        key: "showLines",
        label: "showLines",
        options: ["on", "off"],
        default: "on",
      },
      {
        type: "slider",
        key: "minDistance",
        label: "minDistance",
        min: 10,
        max: 300,
        step: 1,
        default: 150,
      },
      {
        type: "select",
        key: "limitConnections",
        label: "limitConnections",
        options: ["on", "off"],
        default: "off",
      },
      {
        type: "slider",
        key: "maxConnections",
        label: "maxConnections",
        min: 0,
        max: 30,
        step: 1,
        default: 20,
      },
      {
        type: "slider",
        key: "particleCount",
        label: "particleCount",
        min: 0,
        max: 1000,
        step: 1,
        default: 500,
      },
    ],
    load: async () =>
      (await import("./canvas/canvas_buffergeometry_drawrange/easel.js"))
        .example,
    loadThree: async () =>
      (await import("./canvas/canvas_buffergeometry_drawrange/three.js"))
        .example,
  },
  {
    meta: {
      id: "canvas_buffergeometry_indexed",
      upstream: "webgl_buffergeometry_indexed",
      name: "buffergeometry / indexed",
      category: "canvas",
      animated: true,
      description:
        "A 10x10 indexed grid Geometry with per-vertex normals and a red-green gradient over full blue tumbles under a hemisphere light, with a wireframe toggle.",
      differences: [
        "MeshPhongMaterial becomes LambertMaterial with Gouraud (per-vertex) lighting, so the grid has no specular highlight.",
        "The wireframe is drawn by the CPU rasterizer without anti-aliasing.",
      ],
    },
    controls: [
      {
        type: "select",
        key: "wireframe",
        label: "wireframe",
        options: ["on", "off"],
        default: "off",
      },
    ],
    load: async () =>
      (await import("./canvas/canvas_buffergeometry_indexed/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_buffergeometry_indexed/three.js")).example,
  },
  {
    meta: {
      id: "canvas_buffergeometry_lines_indexed",
      upstream: "webgl_buffergeometry_lines_indexed",
      name: "buffergeometry / lines / indexed",
      category: "canvas",
      animated: true,
      description:
        "Four rows of Koch snowflake curves at four iteration depths, drawn as one indexed LineSegments geometry with random per-vertex colors, spinning around the view axis.",
      differences: [],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_buffergeometry_lines_indexed/easel.js"))
        .example,
    loadThree: async () =>
      (await import("./canvas/canvas_buffergeometry_lines_indexed/three.js"))
        .example,
  },
  {
    meta: {
      id: "canvas_buffergeometry_points",
      upstream: "webgl_buffergeometry_points",
      name: "buffergeometry / points",
      category: "canvas",
      animated: true,
      description:
        "A cube of 500,000 points colored by their position tumbles in dark linear fog, drawn from one Geometry with position and color attributes.",
      differences: [
        "EASEL PointsMaterial has no sizeAttenuation and takes an integer pixel radius, so the size-15 points, about 1 pixel square in three.js at this canvas size, become fixed 1-pixel-radius points (a 5-pixel plus shape, 3 pixels wide) that do not grow as they come closer, so the cube reads as a denser, nearly solid block.",
        "Drawing all 500,000 fogged points on the CPU is slow: the median EASEL frame measured about 45 ms at 640x360 in a Bun smoke test, so the animation runs near 22 frames per second instead of the display rate.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./canvas/canvas_buffergeometry_points/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_buffergeometry_points/three.js")).example,
  },
  {
    meta: {
      id: "canvas_worker_offscreencanvas",
      upstream: "webgl_worker_offscreencanvas",
      name: "worker / offscreencanvas",
      category: "canvas",
      animated: true,
      description:
        "One hundred fogged, matcap-shaded icosahedra orbit slowly, with a jank toggle that busy-loops the main thread to show the render loop stalling.",
      differences: [
        "The three.js page shows two canvases: one rendered on the main thread and one transferred to a Web Worker with transferControlToOffscreen. Both sides here mount only the main-thread canvas, because the example viewer takes a context on the stage canvas before setup, writes canvas.width on resize, and needs a synchronous first frame, all of which a transferred canvas cannot provide.",
        "EASEL's Renderer types its canvas option as HTMLCanvasElement, so passing an OffscreenCanvas inside a worker needs a type cast even though the renderer only calls width, height, getContext('2d') and putImageData.",
        "matcap-porcelain-white.jpg has no stated licence, so it is not copied; the three.js side uses MeshMatcapMaterial's built-in grey gradient instead of the porcelain matcap.",
        "EASEL has no MeshMatcapMaterial, so the port uses LambertMaterial lit only by a HemisphereLight whose sky and ground colours reproduce that built-in matcap gradient (0.2 below to 0.8 above in linear light), baked per vertex. The light has no upstream counterpart, so the usual 1/pi intensity scaling does not apply.",
        "The START JANK button becomes a jank select control. Both the three.js and EASEL sides start their own 10,000,000-iteration interval, so turning it on stalls the page about twice as long as the single upstream button, and the result number is not displayed.",
        "The upstream count of 100 icosahedra at detail 8 (162,000 triangles) is kept; at 640x360 the EASEL side measured a median of about 37 ms per frame in the Bun smoke test, over the 33 ms budget.",
      ],
    },
    controls: [
      {
        type: "select",
        key: "jank",
        label: "jank",
        options: ["off", "on"],
        default: "off",
      },
    ],
    load: async () =>
      (await import("./canvas/canvas_worker_offscreencanvas/easel.js")).example,
    loadThree: async () =>
      (await import("./canvas/canvas_worker_offscreencanvas/three.js")).example,
  },
  {
    meta: {
      id: "webaudio_sandbox",
      upstream: "webaudio_sandbox",
      name: "sandbox",
      category: "webaudio",
      animated: true,
      description:
        "Three flat-shaded spheres carry positional sound sources over a grid; click to start the audio, then walk with WASD and drag to look while each sphere glows with its sound's loudness.",
      differences: [
        "Both sides start with the scene already rendered and build the audio graph on the first click on their own canvas, instead of waiting for the upstream START button; cleanup stops every source and closes that side's AudioContext.",
        "The upstream music tracks 358232 and 376737 are CC BY-NC-SA and are not copied, so both sides substitute generated audio: a sawtooth pulsing twice a second on the first sphere and a fast square beat on the second, built from OscillatorNode and GainNode.",
        "The CC0 Project_Utopia ambience is also replaced by a generated slow triangle swell, because the asset was not copied into this repository; it plays as a node source instead of a looping media element.",
        "The generated sources start at once and never end, where the two upstream songs play through once.",
        "EASEL has no Phong material, so the spheres use flat-shaded LambertMaterial without specular.",
        "EASEL's AudioAnalyzer takes an AudioContext and options, so the port creates one per sphere with fftSize 32 and attaches it to that sound's output, where three.js passes the sound to AudioAnalyser.",
        "EASEL FogExp2 evaluates fog per vertex from a lookup table, so the fog fades across each face instead of per pixel.",
      ],
    },
    controls: [
      {
        type: "slider",
        key: "master",
        label: "master",
        min: 0,
        max: 1,
        step: 0.01,
        default: 1,
      },
      {
        type: "slider",
        key: "firstSphere",
        label: "firstSphere",
        min: 0,
        max: 1,
        step: 0.01,
        default: 1,
      },
      {
        type: "slider",
        key: "secondSphere",
        label: "secondSphere",
        min: 0,
        max: 1,
        step: 0.01,
        default: 1,
      },
      {
        type: "slider",
        key: "thirdSphere",
        label: "thirdSphere",
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.5,
      },
      {
        type: "slider",
        key: "Ambient",
        label: "Ambient",
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.5,
      },
      {
        type: "slider",
        key: "frequency",
        label: "frequency",
        min: 50,
        max: 5000,
        step: 1,
        default: 144,
      },
      {
        type: "select",
        key: "wavetype",
        label: "wavetype",
        options: ["sine", "square", "sawtooth", "triangle"],
        default: "sine",
      },
    ],
    load: async () =>
      (await import("./webaudio/webaudio_sandbox/easel.js")).example,
    loadThree: async () =>
      (await import("./webaudio/webaudio_sandbox/three.js")).example,
  },
  {
    meta: {
      id: "misc_controls_map",
      upstream: "misc_controls_map",
      name: "controls / map",
      category: "misc",
      animated: true,
      description:
        "Pan, rotate, and zoom a damped MapControls camera over a fogged city of 500 instanced flat-shaded boxes.",
      differences: [
        "MeshPhongMaterial becomes LambertMaterial with flat shading, so the boxes have no specular highlights.",
        "EASEL FogExp2 evaluates fog per vertex from a lookup table, so the fog fades across each face instead of per pixel.",
      ],
    },
    controls: [
      {
        type: "select",
        key: "zoomToCursor",
        label: "zoomToCursor",
        options: ["on", "off"],
        default: "off",
      },
      {
        type: "select",
        key: "screenSpacePanning",
        label: "screenSpacePanning",
        options: ["on", "off"],
        default: "off",
      },
    ],
    load: async () =>
      (await import("./misc/misc_controls_map/easel.js")).example,
    loadThree: async () =>
      (await import("./misc/misc_controls_map/three.js")).example,
  },
  {
    meta: {
      id: "misc_controls_orbit",
      upstream: "misc_controls_orbit",
      name: "controls / orbit",
      category: "misc",
      animated: true,
      description:
        "Orbit, zoom, and pan a damped OrbitControls camera over a fogged field of 500 instanced flat-shaded cones.",
      differences: [
        "MeshPhongMaterial becomes LambertMaterial with flat shading, so the cones have no specular highlights.",
        "EASEL FogExp2 evaluates fog per vertex from a lookup table, so the fog fades across each face instead of per pixel.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./misc/misc_controls_orbit/easel.js")).example,
    loadThree: async () =>
      (await import("./misc/misc_controls_orbit/three.js")).example,
  },
  {
    meta: {
      id: "misc_controls_pointerlock",
      upstream: "misc_controls_pointerlock",
      name: "controls / pointerlock",
      category: "misc",
      animated: true,
      description:
        "Click the canvas to lock the pointer, then walk with WASD or the arrow keys, jump with Space, and look around with the mouse over a field of 500 colored boxes.",
      differences: [
        "There is no Click to play overlay with instructions; the canvas locks the pointer when clicked, and the keys listen on the focused canvas instead of document.",
        "MeshPhongMaterial becomes LambertMaterial with flat shading, so the boxes have no white specular highlight.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./misc/misc_controls_pointerlock/easel.js")).example,
    loadThree: async () =>
      (await import("./misc/misc_controls_pointerlock/three.js")).example,
  },
  {
    meta: {
      id: "misc_controls_trackball",
      upstream: "misc_controls_trackball",
      name: "controls / trackball",
      category: "misc",
      animated: true,
      description:
        "Rotate, zoom, and pan TrackballControls through a fogged cloud of 500 instanced cones, with a switch between perspective and orthographic cameras.",
      differences: [
        "MeshPhongMaterial becomes LambertMaterial with flat shading, so the cones have no specular highlights.",
        "EASEL FogExp2 evaluates fog per vertex from a lookup table, so the fog fades across each face instead of per pixel.",
      ],
    },
    controls: [
      {
        type: "select",
        key: "orthographicCamera",
        label: "use orthographic",
        options: ["on", "off"],
        default: "off",
      },
      {
        type: "select",
        key: "multiTouchRoll",
        label: "multi touch roll",
        options: ["on", "off"],
        default: "off",
      },
    ],
    load: async () =>
      (await import("./misc/misc_controls_trackball/easel.js")).example,
    loadThree: async () =>
      (await import("./misc/misc_controls_trackball/three.js")).example,
  },
  {
    meta: {
      id: "misc_controls_transform",
      upstream: "misc_controls_transform",
      name: "controls / transform",
      category: "misc",
      animated: true,
      description:
        "Drag the TransformControls gizmo to translate, rotate, or scale a textured crate; keys switch mode, space, snapping, camera, and gizmo size.",
      differences: [
        "Keyboard shortcuts listen on the focused canvas instead of window, so click the canvas before pressing keys; each side of the comparison reacts only to its own keys.",
        "The gizmo keeps the three.js handle layout, picking, and constant screen size, but draws its shafts and rotation rings as lines and its arrow cones with fewer segments so the CPU renderer stays fast.",
        "The 256 x 256 crate texture is scaled to 128 x 128 and sampled with nearest-neighbor, affine UVs, and no anisotropic filtering.",
        "The scene is redrawn every frame instead of only on change events.",
      ],
    },
    controls: [],
    load: async () =>
      (await import("./misc/misc_controls_transform/easel.js")).example,
    loadThree: async () =>
      (await import("./misc/misc_controls_transform/three.js")).example,
  },
  {
    meta: {
      id: "misc_exporter_gcode",
      upstream: "misc_exporter_gcode",
      name: "exporter / gcode",
      category: "misc",
      animated: true,
      description:
        "Place a cube, cylinder, cone, sphere, or torus on a Z-up build plate and slice the selected mesh into G-code text.",
      differences: [
        "EASEL slices with its built-in GCodeExporter, which writes perimeter paths only; three.js loads the external Polyslice library from a CDN, which also applies the printer, filament, and infill settings.",
        "The Printer, Filament, Infill Density, and Infill Pattern controls have no EASEL equivalent and change nothing on the EASEL side; only Layer Height reaches GCodeExporter.",
        "The lil-gui buttons become two select controls: Geometry picks the mesh, and switching Export to Export G-code runs the slicer once.",
        "The export is not downloaded as a .gcode file; both sides log the G-code text length with console.info instead, because the example contract gives the module only a canvas and no place for a status element.",
        "The three.js side still loads Polyslice from cdn.jsdelivr.net, but only when an export is requested, and reports failures with console.error instead of alert().",
        "EASEL bakes Lambert lighting per vertex (Gouraud), so curved shapes show interpolated shading instead of per-pixel lighting.",
      ],
    },
    controls: [
      {
        type: "select",
        key: "printer",
        label: "Printer",
        options: [
          "Ender3",
          "UltimakerS5",
          "PrusaI3MK3S",
          "AnycubicI3Mega",
          "BambuLabP1P",
        ],
        default: "Ender3",
      },
      {
        type: "select",
        key: "filament",
        label: "Filament",
        options: ["GenericPLA", "GenericPETG", "GenericABS"],
        default: "GenericPLA",
      },
      {
        type: "slider",
        key: "layerHeight",
        label: "Layer Height (mm)",
        min: 0.1,
        max: 0.4,
        step: 0.05,
        default: 0.2,
      },
      {
        type: "slider",
        key: "infillDensity",
        label: "Infill Density (%)",
        min: 0,
        max: 100,
        step: 5,
        default: 20,
      },
      {
        type: "select",
        key: "infillPattern",
        label: "Infill Pattern",
        options: ["grid", "triangles", "hexagons"],
        default: "grid",
      },
      {
        type: "select",
        key: "geometry",
        label: "Geometry",
        options: ["Cube", "Cylinder", "Cone", "Sphere", "Torus"],
        default: "Cube",
      },
      {
        type: "select",
        key: "export",
        label: "Export",
        options: ["Idle", "Export G-code"],
        default: "Idle",
      },
    ],
    load: async () =>
      (await import("./misc/misc_exporter_gcode/easel.js")).example,
    loadThree: async () =>
      (await import("./misc/misc_exporter_gcode/three.js")).example,
  },
  {
    meta: {
      id: "misc_exporter_obj",
      upstream: "misc_exporter_obj",
      name: "exporter / obj",
      category: "misc",
      animated: true,
      description:
        "Switch between a triangle, primitives, transformed objects, and a point cloud, then serialize the scene to Wavefront OBJ text with OBJExporter.",
      differences: [
        "The lil-gui buttons become two select controls: Geometry picks the scene, and switching Export to Export OBJ runs the exporter once.",
        "The export is not downloaded as object.obj; both sides log the exported text length with console.info instead, because the example contract gives the module only a canvas and no place for a status element.",
        "EASEL OBJExporter serializes only meshes, so the Point Cloud export has no vertex or p lines, where three.js writes the four colored points.",
        "EASEL OBJExporter writes its own header and comments (for example easel-material-color), so the text differs from the three.js exporter output.",
        "EASEL Points with vertexColors averages the colors of each run of three points, so the first three points of the Point Cloud draw in one brown color instead of red, red, and green.",
        "EASEL PointsMaterial.size is a fixed pixel radius, so the 10 unit points draw larger on screen and keep their pixel size at every zoom level.",
        "EASEL bakes Lambert lighting per vertex (Gouraud), so the lit faces show interpolated shading instead of per-pixel lighting.",
      ],
    },
    controls: [
      {
        type: "select",
        key: "geometry",
        label: "Geometry",
        options: [
          "Triangle",
          "Cube",
          "Cylinder",
          "Multiple objects",
          "Transformed objects",
          "Point Cloud",
        ],
        default: "Triangle",
      },
      {
        type: "select",
        key: "export",
        label: "Export",
        options: ["Idle", "Export OBJ"],
        default: "Idle",
      },
    ],
    load: async () =>
      (await import("./misc/misc_exporter_obj/easel.js")).example,
    loadThree: async () =>
      (await import("./misc/misc_exporter_obj/three.js")).example,
  },
];
