import { Vector3 } from "../../math/Vector3.ts";
import { Geometry } from "../Geometry.ts";

function buildParametricIndices(
  sliceCount: number,
  stackCount: number,
): number[] {
  const indices: number[] = [];
  for (let i = 0; i < stackCount; i++) {
    for (let j = 0; j < sliceCount; j++) {
      const a = i * (sliceCount + 1) + j;
      const b = a + 1;
      const d = (i + 1) * (sliceCount + 1) + j;
      const c = d + 1;
      indices.push(a, b, d, b, c, d);
    }
  }
  return indices;
}

/** Writes a point on a parametric surface into the target vector. */
export type ParametricFunction = (
  u: number,
  v: number,
  target: Vector3,
) => Vector3 | undefined;

/** CPU geometry generated by sampling a two-parameter surface function. */
export class ParametricGeometry extends Geometry {
  /** Samples a parametric surface into indexed triangles with finite-difference normals. */
  constructor(
    func: ParametricFunction = (u: number, v: number, target: Vector3) =>
      target.set(u, v, Math.cos(u) * Math.sin(v)),
    slices: number = 8,
    stacks: number = 8,
  ) {
    super();
    this.type = "ParametricGeometry";
    const sliceCount = Math.max(1, Math.floor(slices));
    const stackCount = Math.max(1, Math.floor(stacks));
    this.parameters = { func, slices: sliceCount, stacks: stackCount };

    const positions: number[] = [];
    const normals: number[] = [];
    const uvs: number[] = [];
    const epsilon = 1e-5;
    const position = new Vector3();
    const sample = new Vector3();
    const tangentU = new Vector3();
    const tangentV = new Vector3();
    const normal = new Vector3();

    for (let i = 0; i <= stackCount; i++) {
      const v = i / stackCount;
      for (let j = 0; j <= sliceCount; j++) {
        const u = j / sliceCount;
        func(u, v, position);
        positions.push(position.x, position.y, position.z);

        if (u >= epsilon) {
          func(u - epsilon, v, sample);
          tangentU.subVectors(position, sample);
        } else {
          func(u + epsilon, v, sample);
          tangentU.subVectors(sample, position);
        }
        if (v >= epsilon) {
          func(u, v - epsilon, sample);
          tangentV.subVectors(position, sample);
        } else {
          func(u, v + epsilon, sample);
          tangentV.subVectors(sample, position);
        }
        normal.crossVectors(tangentU, tangentV).normalize();
        normals.push(normal.x, normal.y, normal.z);
        uvs.push(u, v);
      }
    }

    const indices = buildParametricIndices(sliceCount, stackCount);
    const IndexArray = positions.length / 3 > 65535 ? Uint32Array : Uint16Array;
    this.setPositions(new Float32Array(positions));
    this.setNormals(new Float32Array(normals));
    this.setUVs(new Float32Array(uvs));
    this.index = new IndexArray(indices);
    this.computeBoundingSphere();
  }
}
