// Regenerates www/examples/registry.ts from the example modules.
// Each www/examples/<category>/<id>/ pair contributes its own `meta` and
// `controls`; entries follow their `meta.upstream` order in three.js r186
// examples/files.json, vendored as scripts/three-examples-r186.json.
// `--check` fails when the checked-in registry differs from the generated one.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import process from "node:process";

const CATEGORY_ORDER = ["canvas", "webaudio", "physics", "misc"] as const;

interface ExampleModule {
  meta: { id: string; upstream: string };
  controls?: unknown[];
}

const root = resolve(import.meta.dir, "..");
const examplesDir = join(root, "www/examples");
const registryPath = join(examplesDir, "registry.ts");
const threeFiles = JSON.parse(
  readFileSync(join(root, "scripts/three-examples-r186.json"), "utf8"),
) as Record<string, string[]>;
const order = Object.values(threeFiles).flat();

// EASEL renders with Canvas2D, so three.js `webgl_` ids become `canvas_`.
const easelId = (upstream: string): string =>
  upstream.startsWith("webgl_") ? `canvas_${upstream.slice(6)}` : upstream;

const found: { id: string; category: string; module: ExampleModule }[] = [];
for (const category of CATEGORY_ORDER) {
  const dir = join(examplesDir, category);
  if (!existsSync(dir)) continue;
  for (const id of readdirSync(dir).sort()) {
    const easel = join(dir, id, "easel.js");
    if (!existsSync(easel) || !existsSync(join(dir, id, "three.js"))) continue;
    const module = (await import(easel)) as ExampleModule;
    const { upstream } = module.meta;
    if (!order.includes(upstream)) {
      throw new Error(
        `${category}/${id}: ${upstream} is not a three.js r186 example id`,
      );
    }
    if (module.meta.id !== id || easelId(upstream) !== id) {
      throw new Error(
        `${category}/${id}: meta.id must be ${easelId(upstream)}`,
      );
    }
    found.push({ id, category, module });
  }
}
found.sort(
  (a, b) =>
    order.indexOf(a.module.meta.upstream) -
    order.indexOf(b.module.meta.upstream),
);

const literal = (value: unknown, indent: string): string =>
  JSON.stringify(value, null, 2)
    .replace(/"([A-Za-z_$][\w$]*)":/g, "$1:")
    .split("\n")
    .map((line, index) => (index === 0 ? line : indent + line))
    .join("\n");

const categories = CATEGORY_ORDER.filter((category) =>
  found.some((entry) => entry.category === category),
);
let output = `import type { ExampleRegistryEntry } from "../loaders/examples.ts";

// Generated by \`bun run examples:registry\` from each example's own meta and
// controls, in three.js r186 examples/files.json order of meta.upstream.
// Do not edit by hand.
export const categoryLabels = {
${categories.map((category) => `  ${category}: "${category}",`).join("\n")}
} as const;

export const examples: ExampleRegistryEntry[] = [
`;
for (const { id, category, module } of found) {
  output += `  {
    meta: ${literal(module.meta, "    ")},
    controls: ${literal(module.controls ?? [], "    ")},
    load: async () =>
      (await import("./${category}/${id}/easel.js")).example,
    loadThree: async () =>
      (await import("./${category}/${id}/three.js")).example,
  },
`;
}
output += "];\n";

// Format like the rest of the repository so --check compares like with like.
const formatted = Bun.spawnSync(
  ["bunx", "biome", "format", "--stdin-file-path", registryPath],
  { cwd: root, stdin: new TextEncoder().encode(output) },
);
if (formatted.exitCode !== 0) {
  process.stderr.write(formatted.stderr.toString());
  process.exit(1);
}
const text = formatted.stdout.toString();

if (process.argv.includes("--check")) {
  if (readFileSync(registryPath, "utf8") !== text) {
    process.stderr.write(
      "www/examples/registry.ts is stale; run bun run examples:registry\n",
    );
    process.exit(1);
  }
  process.stdout.write(`example registry OK: ${found.length} entries\n`);
} else {
  writeFileSync(registryPath, text);
  process.stdout.write(`wrote ${found.length} example entries\n`);
}
