name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

concurrency:
  group: cloudflare-pages-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  NODE_VERSION: lts/*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: oven-sh/setup-bun@v2.2.0
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: bun install --frozen-lockfile
      - run: bun run www:build
      - uses: cloudflare/wrangler-action@v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/www --project-name=easeljs
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
